# NumPy

In [7]:
#Import Numpy Library

import numpy as np
from numpy import random

In [2]:
#create simple array from the list 

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim # dimention

2

In [4]:
arr.shape #shape of array

(2, 4)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.data #memory location

# Random Number Generator uing numpy

In [10]:
#For integer number

x= random.randint(1000)
x

526

In [11]:
x= random.randint(1000)
x

153

In [12]:
x= random.randint(100)
x

75

In [16]:
#for Float number

x= random.rand()
x

0.8990702652393825

In [17]:
x= random.rand(5)
x

array([0.56696237, 0.79784385, 0.65985529, 0.37213913, 0.42550487])

In [19]:
x= random.randint(100, size=(5))
x

array([19, 10, 15, 84, 32])

In [20]:
x= random.randint(100, size=(5,3))
x

array([[27, 51, 83],
       [21, 95, 79],
       [40, 50, 81],
       [88, 32, 87],
       [95, 29, 63]])

In [26]:
#a=1D array ,with 7 integer
#b=1D array ,with 7 integer
#math opearation.

a= random.randint(100, size=(7))
print(a)
b= random.randint(100, size=(7))
print(b)

z= a+b
print(z)

[26 24 62 18 34 28 60]
[11 19 56 87 70 16 73]
[ 37  43 118 105 104  44 133]


# Matrix in Numpy

In [27]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [30]:
b=np.matrix('1 2 3; 4 5 6; 7 8 9')
b

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
type(b)

numpy.matrix

In [33]:
n = np.matrix([[1,2,3],[5,6,7], [8,9,1]])
n

matrix([[1, 2, 3],
        [5, 6, 7],
        [8, 9, 1]])

# Measure of central Tendency

In [38]:
arr = np.array([[11,22,33],[55,66,77],[99,88,77]])
arr

array([[11, 22, 33],
       [55, 66, 77],
       [99, 88, 77]])

In [39]:
np.amin(arr) #min value

11

In [40]:
np.amax(arr) #max value

99

In [42]:
np.mean(arr) #mean value

58.666666666666664

In [43]:
np.median(arr) #median value

66.0

In [45]:
np.std(arr) #std. deviation

28.871362204709975

In [49]:
np.var(arr) 

833.5555555555555